name: Deploy Portfolio to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build Site
        run: |
          mkdir -p public
          cp -r * public/   # assumes static site files in repo root
          echo "yourdomain.com" > public/CNAME  # custom domain

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_USERNAME: "GitHub Actions"
          SLACK_TITLE: "🚀 GitHub Pages Deployment Completed"
          SLACK_MESSAGE: "Portfolio site deployed successfully!"
